MVCProjectBlog/MVCProjectBlogNew/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogClassLibrary;

using BlogClassLibrary.DataAccessLayer;
using Microsoft.AspNet.Identity;
using MVCProjectBlogNew.Models;

namespace MVCProjectBlog.Controllers
{
    public class BlogController : Controller
    {

        public ActionResult Post(string PostId)
        {
            var db = new Repository();
            var model = db.ReturnBlogWithOnePost(PostId);
            return View(model);


        }

        public ActionResult Edit(string id)
        {
            var db = new Repository();
            var model = db.ReturnBlogWithOnePost(id);
            return View(model);
        }

        [HttpPost]
        
        public ActionResult Edit(Post updated)
        {
            if (ModelState.IsValid)
            {
                var db = new Repository();
                db.UpdatePost(updated);

                return RedirectToAction("Index", new {BlogId = db.GetBlogIdFromPostId(updated.Id)});
            }
            else
            {
                return View(updated);
            }
            
        }


        public ActionResult Index(string BlogId)
        {

            var repository = new Repository();
            var model = repository.ReturnBlogs(BlogId);
            return View(model);

        }
        [Authorize]
        public ActionResult SubmitPost(int id)
        {


            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult SubmitPost(int id, CreateBlogPost createdPost)
        {
            if (ModelState.IsValid)
            {
                var db = new Repository();

                db.InsertNewBlogPost(createdPost, id);

                return RedirectToAction("Index", new {BlogId = id});
            }
            else
            {
                return View(createdPost);
            }
            
        }

        public ActionResult Insert(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Insert(int id, CreateBlogPost createdPost)
        {

            
            var db = new Repository();
            

            db.InsertNewBlogPost(createdPost,id);

            return RedirectToAction("Index", new { BlogId = id });
        }

        

        public ActionResult GetPostsWithHashtags(string tag)
        {
            Repository DB = new Repository();
            var model = DB.GetAllPostsContainingSpecificHashtag(tag);
            return View(model);
        }
        
        public ActionResult PostANewComment(int Postid)
        {
            var model = new Comment();
            return PartialView(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostANewComment(Comment comment, int Postid)
        {
            if (ModelState.IsValid)
            {
                var DB = new Repository();
                DB.AddCommentToPost(comment,Postid);
                var model = new Comment();
                return PartialView(model);
            }

            return PartialView(comment);


             
      
         
 


        }

        public ActionResult Delete(string id)
        {
            var DB = new Repository();
            var model = DB.ReturnBlogWithOnePost(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var db = new Repository();
            var blogId = db.GetBlogIdFromPostId(id);
            db.DeletePost(id);
            return RedirectToAction("Index", new { BlogId = blogId });
        }

        public ActionResult About(int blogId)
        {
            var DB = new Repository();
            var model = DB.GetBlogWithId(blogId);
            return View(model);
        }

        
    }
}

MVCProjectBlog/MVCProjectBlogNew/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogClassLibrary;
using BlogClassLibrary.DataAccessLayer;
using Microsoft.AspNet.Identity;

namespace MVCProjectBlog.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var repository = new Repository();
            var model = repository.ReturnBlogs();
            return View(model);
        }

        public ActionResult CarousellPosts()
        {
            var repository = new Repository();
            var model = repository.ReturnPostsToMainCarousell();
            model = model.Take(4).ToList();
            return PartialView("CarousellPosts",model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Owner owner)
        {
            var Db = new Repository();
            Db.AddNewOwnerAccount(owner);
            

            return View(owner);
        }
        public ActionResult Register()
        {
            var model = new Owner();
            return View(model);
        }



        public ActionResult Login()
        {
           
            return PartialView("_Login");
        }

        public ActionResult _HashTags()
        {
            var repository = new Repository();
            var model = repository.ReturnTenHashtags();
            return PartialView("_Hashtags",model);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Search(string term)
        {
            var db = new Repository();

            //List<Hashtag> hasttaglist = db.GetHashtagsThatContainString(term);
            return PartialView("_SearchResult", db.GetHashtagsThatContainString(term));
        }

        public JsonResult SearchAutoComplete(string term)
        {
            var db = new Repository();
            return Json(db.GetHashtagsThatContainString(term), JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult CreateBlog(int ownerId)
        {
            var DB = new Repository();
            var blog = new Blog();
            int id = DB.ReturnOwnerId(User.Identity.GetUserName());
            return View(blog);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBlog(Blog blog,int ownerId)
        {
            var DB = new Repository();
            DB.AddBlogToDatabase(blog,ownerId);
            return View(blog);
        }

        public ActionResult _postHeader()
        {
            var DB = new Repository();
            var model = DB.GetPostHeaderByDate();
            return PartialView("_postHeader",model);
        }


       
    }
}

MVCProjectBlog/MVCProjectBlogNew/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogClassLibrary.DataAccessLayer;

namespace MVCProjectBlog.Controllers
{
    public class PostController : Controller
    {
        // GET: Post
        public ActionResult Index(string id)
        {
            var DB = new Repository();
            var model = DB.GetPostWithBlogName(id);

            return View(model);
        }
    }
}

MVCProjectBlog/MVCProjectBlogNew/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Styles/ViewStyles/HomeViewStyle.css" rel="stylesheet" />
<div class="col-md-9 blogMainContent">
    <h2>About Raj</h2>

    <h3>Developers</h3>
    <ul>
        <li>
            <strong>R</strong>obin Bergström
        </li>
        <li>
            <strong>A</strong>ndreas Ekwall
        </li>
        <li>
            <strong>J</strong>akob Stjernholm
        </li>
    </ul>

    <hr />

    <p>
        This blog is made because of a project in a course called MVC(Model View Controller).<br />
        We are all three students at EC-Utbildning located in Hesingborg, Sweden.
        We were all beginners at MVC and this is the first MVC-project we are involved in, and we did it in only <strong>2-3 weeks</strong>.
        We hope you will enjoy your stay at our blog portal and will be happy to see you @Html.ActionLink("register", "Register", "Home") and start blogging!
    </p>
    <hr />

    <h4>Contacts</h4>
    <ul class="contactEmailClass">
        <li>robin.bergstrom.win14@HermodsAB.onmicrosoft.com</li>
        <li>andreas.ekwall.win14@HermodsAB.onmicrosoft.com</li>
        <li>jakob.stjernholm.win14@HermodsAB.onmicrosoft.com</li>
    </ul>
</div>
<div class="col-md-3 sidebarContent">
    <div class="container">
        <div class="row">
            <div class="col-md-12 sidebarContentPlaceholder">


                <h3>Search</h3>

                @using (Ajax.BeginForm("SearchAutoComplete", "Home", new AjaxOptions
                        {
                            UpdateTargetId = "search_results"
                        }))
                {
                    <input type="text" id="search_term" />
                    <input type="submit" value="Go!" />
                }


            </div>
            <div class="col-md-12 sidebarContentPlaceholder">

                <h5>Latest Posts</h5>

                @Html.Action("_postHeader")

            </div>
            <div class="col-md-12 sidebarContentPlaceholder">
                <h5>Top-25 Hashtags</h5>

                @Html.Action("_HashTags")

            </div>
        </div>
    </div>

</div>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/CarousellPosts.cshtml
@model  List<BlogClassLibrary.Post>
           
<div class="col-md-12 slideshowContainer">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            
        </ol>
        
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">

                @*http://www.cisny.com/wp-content/uploads/2011/08/boat-918x349.jpg
                http://www.kamfineartphoto.com/uploads/1/6/5/6/16567096/2120472_orig.jpg*@

                <img class="carouselImage" src="http://www.kamfineartphoto.com/uploads/1/6/5/6/16567096/2120472_orig.jpg" alt="...">
                @*http://bishnoivillage.com/wp-content/uploads/2014/09/banner4.jpg
     http://bishnoivillage.com/wp-content/uploads/2014/09/banner5.jpg
     http://eye-inspire.com/wp-content/uploads/2013/05/slider3.jpg
    http://christianinsights.com.au/wp-content/uploads/2013/04/slide3.jpg*@
                <div class="carousel-caption">

                    <h3 class="CarouselH3">Welcome to the RAJ Blog Portal. Your new favourite home on the web!</h3>
                    <h4>@Html.ActionLink("Register New Account Today", "Register", "Home")</h4>
                </div>
            </div>
          

            
                @foreach (var post in Model)
                {
                    <div class="item">
                        <img class="carouselImage" src="@Html.DisplayFor(modelItem => post.Blog.BackgroundImage)" alt="...">
                        <div class="carousel-caption">
                            <h3 class="CarouselH3">@Html.DisplayFor(modelItem => post.Header)</h3>
                            @Html.ActionLink(post.Header, "Post", "Blog", new { PostId = post.Id}, null)

                            @*@Html.ActionLink(item.Name, "Index", "Blog", new { BlogId = item.Id }, null)*@
                        </div>
                    </div>
                }
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div> <!-- Carousel -->
</div>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/CreateBlog.cshtml
@model BlogClassLibrary.Blog

@{
    ViewBag.Title = "CreateBlog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateBlog</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BackgroundImage, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.BackgroundImage, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.BackgroundImage, "", new {@class = "text-danger"})
            </div>
        </div>
        <div>
            <h3>Copy and one of the links to add a theme picture to your blog</h3>
            <p> This is a work in progress</p>
            <p> <strong>Life, Nature:</strong>http://www.cccwt.org.uk/communities/4/004/012/867/704//images/4615066949_918x349.jpg </p>
            <p> <strong>Books, Religion:</strong>http://christianinsights.com.au/wp-content/uploads/2013/04/bible-verse3.jpg</p>
            <p> <strong>Birds:</strong>http://birdtourchina.com/wp-content/uploads/2013/11/Yellow-throated-Laughingthrush.jpg</p>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Home</h2>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/Index.cshtml
@using System.Web.Mvc.Html
@using Microsoft.AspNet.Identity
@model IEnumerable<BlogClassLibrary.Blog>

@{
    ViewBag.Title = "Index";
}
<link href="~/Styles/ViewStyles/HomeViewStyle.css" rel="stylesheet" />
@*<link href="~/Styles/ViewStyles/HomeViewStyleTest.css" rel="stylesheet" />*@
<div class="container">
    <div class="row">

        <div class="col-md-9 mainContent">
            <div class="container">
                <div class="row">
                  @Html.Action("CarousellPosts")
                    @foreach (var item in Model)
                    {
                        <div class="col-md-3 AvailableBlogsContainer">

                            <h3 class="h3AvailableBlogsHeaderLink">
                                @*@Html.ActionLink(item.Name, "Index", "Post", new {id = item.Name}, null)*@
                                @Html.ActionLink(item.Name, "Index", "Blog", new {BlogId = item.Id}, null)

                            </h3>

                            <p class="ParagraphAvailableBlogsDescription">@Html.DisplayFor(modelItem => item.Description)</p>


                            

</div>
                       
                    }
                </div>
            </div>

            

        </div>
        <div class="col-md-3 sidebarContent">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 sidebarContentPlaceholder">
                        
                       
                        <h3>Search</h3>

                        @using (Ajax.BeginForm("SearchAutoComplete", "Home", new AjaxOptions
                        {
                            UpdateTargetId = "search_results"
                        }))
                        {
                            <input type="text" id="search_term" />
                            <input type="submit" value="Go!" />
                        }
                        

                    </div>
                    <div class="col-md-12 sidebarContentPlaceholder">

                        <h5>Latest Posts</h5>

                            @Html.Action("_postHeader")
                       
                    </div>
                    <div class="col-md-12 sidebarContentPlaceholder">
                        <h5>Top-25 Hashtags</h5>
                            
                                @Html.Action("_HashTags")

                    </div>
                </div>
             </div>

        </div>



   </div>
</div>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/Register.cshtml
@model BlogClassLibrary.Owner

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Owner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Raj blogportal", "Index")
</div>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/_HashTags.cshtml
@model IEnumerable<BlogClassLibrary.Hashtag>




@foreach (var item in Model)
{

    <p class="HashtagParagraph">@Html.ActionLink(item.Tag + "  ", "GetPostsWithHashtags", "Blog", new { tag = item.Tag }, null)</p>

}

MVCProjectBlog/MVCProjectBlogNew/Views/Home/_PostHeader.cshtml
@model IEnumerable<BlogClassLibrary.Post>

@foreach (var item in Model)
{
    <p>@Html.ActionLink(item.Header, "Post", "Blog", new {postid = item.Id}, null) <br/>
    </p>
    
}

MVCProjectBlog/MVCProjectBlogNew/Views/Home/_SearchResult.cshtml
@model IEnumerable<BlogClassLibrary.Hashtag>

<p>
    <h3>Search result</h3>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tag)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Tag)
        </td>
       
    </tr>
}

</table>

MVCProjectBlog/MVCProjectBlogNew/Views/Home/tinymce_full.cshtml
<script src="@Url.Content("~/Scripts/tinymce/tiny_mce.js")" type="text/javascript"></script>

<script type="text/javascript">

    (function(){ 

        tinyMCE.init({

            // General options
            mode: "exact",
            elements: "@ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty)",
            theme: "advanced",
            height: "500",
            width: "790",
            verify_html : false,
		    plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

		    // Theme options
		    theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,codehighlighting,netadvimage",
		    theme_advanced_toolbar_location : "top",
		    theme_advanced_toolbar_align : "left",
		    theme_advanced_statusbar_location : "bottom",
		    theme_advanced_resizing : false,

		    // Example content CSS (should be your site CSS)
		    //content_css : "css/content.css",
            content_css : "@Url.Content("~/Scripts/tinymce/css/content.css")",
            convert_urls : false,

		    // Drop lists for link/image/media/template dialogs
		    template_external_list_url : "lists/template_list.js",
		    external_link_list_url : "lists/link_list.js",
		    external_image_list_url : "lists/image_list.js",
		    media_external_list_url : "lists/media_list.js",

	    });

    })();

</script>

@Html.TextArea(string.Empty, /* Name suffix */
    ViewData.TemplateInfo.FormattedModelValue /* Initial value */
)

MVCProjectBlog/MVCProjectBlogNew/Views/Home/tinymce_full_compressed.cshtml
<script src="@Url.Content("~/Scripts/tinymce/tiny_mce.js")" type="text/javascript"></script>

<script type="text/javascript">
(function(){tinyMCE.init({mode:"exact",elements:"@ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty)",theme:"advanced",height:"500",width:"790",verify_html:false,plugins:"pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",theme_advanced_buttons1:"save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",theme_advanced_buttons2:"cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",theme_advanced_buttons3:"tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",theme_advanced_buttons4:"insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,codehighlighting,netadvimage",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_statusbar_location:"bottom",theme_advanced_resizing:false,content_css:"@Url.Content("~/Scripts/tinymce.3.4.5/css/content.css")",convert_urls:false,template_external_list_url:"lists/template_list.js",external_link_list_url:"lists/link_list.js",external_image_list_url:"lists/image_list.js",media_external_list_url:"lists/media_list.js",})})();
</script>

@Html.TextArea(string.Empty, /* Name suffix */
    ViewData.TemplateInfo.FormattedModelValue /* Initial value */
)